server:
  port: 8016

application:
  base-packages:  com.datasensorn.mqttservice
  scheduler:
    rate: 5000
  mqtt:
    hostUrl: tcp://101.37.146.78:61613
    client:
      inBoundId: ${random.value}
      outBoundId:  ${random.value}
    topic: UP/#
    username: admin
    password: password
    timeout:  10
    completionTimeout:  3000
    heartbeat:  10
# 天气预报API（阿里）
  weather:
    AppCode:  e16633309c1940cd8170272912e54a12
    host: http://ali-weather.showapi.com
    path: /area-to-weather
# APK 下载升级管理相关配置
  storeFilePath:  appFile/store

jasypt:
  encryptor:
    password: sodmewuhan

spring:
#mysql 数据库
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    driver-class-name: com.mysql.cj.jdbc.Driver
    platform: mysql
    url:  jdbc:mysql://101.37.146.78:3306/datasensorn?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: ENC(3MSmXyIfYr45wWfphZlFHQ==)
    password: ENC(tuNUWfAXpWVB1PZK6g75r0qth7yPMH1/)
    initialSize: 5
    minIdle: 5
    maxActive: 30
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    filters: stat,wall,log4j
    logSlowSql: true
#influxdb 数据库
  influxdb:
      url: http://101.37.146.78:8086
      username: admin
      password: admin
      database: fishtech
      connecttimeout: 10
      readtimeout: 30
      timeout: 10
      retentionpolicy: saveThreeMonth
      duration: 180d  #数据默认保存180天
      replicationNum: 1 #数据默认保存1份
# thymeleaf 配置
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache:  false
    mode: HTML5
#redis  jwt 使用
  redis:
    # Redis服务器地址
    host: 101.37.146.78
    # Redis服务器连接端口
    port: 6379
mybatis:
  mapper-locations: classpath:mapping/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.datasensorn.mqttservice.model.biz  # 注意：对应实体类的路径

