application:
  base-packages:  com.datasensorn.mqttservice
  scheduler:
    rate: 5000
  mqtt:
    host: tcp://iot.eclipse.org:1883
    publisher:  sodmewuhan-publisher
    subscriber: sodmewuhan-subscriber
    topic:  /sodmewuhan/test

spring:
  datasource:
    url:  jdbc:mysql://192.168.152.130:3306/datasensorn?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    driver-class-name:  com.mysql.jdbc.Driver