server:
  port: 8011

application:
  base-packages:  com.datasensorn.mqttservice
  scheduler:
    rate: 5000
  mqtt:
    hostUrl: tcp://101.37.146.78:61613
    client:
      id: ${random.value}
    topic: UP/#
    username: admin
    password: password
    timeout:  10
    heartbeat:  20
  weather:
    AppCode:  e16633309c1940cd8170272912e54a12
    host: http://ali-weather.showapi.com
    path: /hour24

spring:
#mysql 数据库
  datasource:
    url:  jdbc:mysql://101.37.146.78:3306/datasensorn?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: hello123456
    driver-class-name: com.mysql.jdbc.Driver
#influxdb 数据库
  influxdb:
      url: http://101.37.146.78:8086
      username: admin
      password: admin
      database: fishtech
      connecttimeout: 10
      readtimeout: 30
      timeout: 10
# thymeleaf 配置
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache:  false
    mode: HTML

## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  mapper-locations: classpath:mapping/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.datasensorn.mqttservice.model.biz  # 注意：对应实体类的路径